### ISSUE TITLE
plz fix this glitch

### ISSUE THREAD

**Issue by achrafhkdk** [qbcore-framework/qb-crypto#2]
I can take Unlimited money
plz fix it
![image](https://user-images.githubusercontent.com/44878760/122198486-1c946880-ce91-11eb-93d8-842303be40f8.png)

**Comment by Manliketjb** [comment]
> I can take Unlimited money
> plz fix it
> ![image](https://user-images.githubusercontent.com/44878760/122198486-1c946880-ce91-11eb-93d8-842303be40f8.png)

Not a glitch.. your crypto worth is nothing.. make it Worth something then it wouldn't be free

**Comment by JericoFX** [comment]
can you give more details about it?

**Comment by achrafhkdk** [comment]
if tap fast you can get any number money

**Comment by JericoFX** [comment]
Ok check this https://github.com/qbcore-framework/qb-phone/pull/15 modify manually and tell me if works

**Comment by GhzGarage** [comment]
Fixed
