### ISSUE TITLE
*sometimes* value resets to 0 after restart?

### ISSUE THREAD

**Issue by ammopack** [qbcore-framework/qb-crypto#25]
Seems that randomly without any tell or errors, the value of crypto will reset to 0 after a server restart? I have no idea what is going on, anybody else have this issue? Sorry for posting I asked on CFX forums but no one got back to me.
Everything is updated, fresh install.

**Comment by GhzGarage** [comment]
@pushkart2

**Comment by pushkart2** [comment]
There is an issue where people are not updating the database. make sure crypto is primary key. Then clear the complete table and st crypto value using /setcryptoworth qbit 100

you can set 100 or whatever you want.

**Comment by ammopack** [comment]
We have to manually update the crypto price...? I'm a bit confused? Looks like it changes its value just fine. Like I stated, it will reset to 0(zero) after a restart, sometimes. Not every time.

**Comment by ammopack** [comment]
I tried your fix @pushkart2 but it still seems to reset, whenever somebody who isnt me logs into the server

**Comment by ammopack** [comment]
It will still randomly reset but i put it to 50 in the config. Kinda a bummy work around, but it should work.
