### ISSUE TITLE
Crypto buy and sell 

### ISSUE THREAD

**Issue by leoyassir** [qbcore-framework/qb-crypto#32]
probleme when you buy or sell , you can buy how much you need with 0 ,you need to do what i do in this video so fast  https://streamable.com/qeikra ,

**Comment by Mitroxs** [comment]
Close this as its solved in latest PR

**Comment by leoyassir** [comment]
its not still same glitch

**Comment by Mitroxs** [comment]
ah fuck i forgot something

**Comment by Mitroxs** [comment]
> Ah alright, i must have forgot the last part. Well should be fixed after this last pr #37

Fixed on server side now, and once the PR in the phone part gets pulled. The problem should be fully mitigated

**Comment by leoyassir** [comment]
yeah now it's working well thank you
