### ISSUE TITLE
[SUGGESTION] add more life crypto

### ISSUE THREAD

**Issue by alfiswielki** [qbcore-framework/qb-crypto#58]
można dodać więcej crypto.
eth,ada,btc,sol,
with real prices from the market

**Comment by Molicheu** [comment]
This is already an option, go into qb-crypto then go into the config.lua and go all the way down to the bottom. Here you will see a table called Ticker, inside that table you will see Enabled = false, make it true for real-time prices

**Comment by alfiswielki** [comment]
> To już jest opcja, przejdź do qb-crypto, a następnie przejdź do config.lua i zejdź na sam dół. Tutaj zobaczysz tabelę o nazwie Ticker, wewnątrz tej tabeli zobaczysz Enabled = false, spraw, aby była prawdziwa dla cen w czasie rzeczywistym

ok and how to add other crypto? eth,ada,sol?
